### ISSUE TITLE
Raspberry Pi camera 

### ISSUE THREAD

**Issue by Murali-IsPagro** [Pallav1299/ROS_aruco_detection#1]
Hi,

I am using Raspberry pi camera v2 with CSI interface. I am using raspicam_node 
installed from [https://github.com/UbiquityRobotics/raspicam_node]

I am Using marker id no 12, where to specify in the code or it should be added in launch file.

Thanks

**Comment by pallavbhalla** [comment]
@Murali-IsPagro, it's been a while since I worked on this.

- Do have a look at the camera driver. The one I used was usb_camera driver.
- Regarding the Aruco marker ID, you need to define the Aruco dictionary in the python file. You will get the identified ID from that dictionary of aruco markers.

**Comment by Murali-IsPagro** [comment]
Sure, Will try these out.
